# Generated by Django 6.0.6 on 2026-07-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('search_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-search_at'],
            },
        ),
    ]
